# Slab generation configuration settings

projection_method: ['mip', 'soft_mip', 'aip']
thickness_overlap: [[10, 5],[10, 0], [6, 3], [6, 0], [8, 4], [8, 0], [12, 6], [12, 0], [14, 7], [14, 0]]
slice_skip_ratio: [[0.05, 0.05]]    # [top, bottom] slice selection ratio to skip in slab generation
breast_skin_removal: [0, 1]         # 0: no removal, 1: with removal
breast_skin_kernel_size: [7]        # 3, 5, 7 | radius with lower resolution (scale = 0.25)
breast_skin_iteration_number: [1]   # iteration number for erosion operation
